name: redis-task

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA_PATH}:/data/redis
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  app:
    build:
      context: ${PHP_DOCKERFILE_PATH}
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: ${PHP_WORKDIR}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../:/var/www
    depends_on:
      - redis
      - nginx
      - postgres
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql