name: ${PROJECT_NAME}
services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
     - "${NGINX_PORT}:80"
    volumes:
      - ../app:/var/www
      - ./nginx:/etc/nginx/conf.d
  php:
    build:
      context: ${PHP_DOCKERFILE_PATH}
      dockerfile: Dockerfile
    container_name: php
    restart: always
    working_dir: ${PHP_WORKDIR}
    volumes:
      - ../app:/var/www
    depends_on:
      - db
      - nginx
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data